name: CI Covid19 Notification

on: push

jobs:
  run-test:
    env:
      APP_CENTER_TOKEN: ${{secrets.APP_CENTER_TOKEN}}
      APP_CENTER_APP: ${{secrets.APP_CENTER_APP}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate checksum gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check for code formatting violations
        run: ./gradlew spotlessCheck

      - name: Build app
        run: ./gradlew app:assemDevDebug app:assemAndroidTest testDevDebug testDebug app:lintDevDebug

      - name: Run instrumentation tests
        uses: minvws/AppCenter-Github-Action@v1.0.3
        if: ${{ env.APP_CENTER_TOKEN }}
        with:
          command: appcenter test run espresso --app ${{env.APP_CENTER_APP}} --devices belastingdienst/vws-covid-19-notificatie-instrumentation-test --app-path app/build/outputs/apk/dev/debug/covid-notificatie-dev-debug.apk --test-series master --locale en_US --test-apk-path app/build/outputs/apk/androidTest/dev/debug/covid-notificatie-dev-debug-androidTest.apk
          token: ${{secrets.APP_CENTER_TOKEN}}